version: "3.9"

services:
  bot:
    build: .
    container_name: telegram_bot
    env_file:
      - .env
    depends_on:
      - redis
    environment:
      REDIS_URL: ${REDIS_URL}
    restart: always

  redis:
    image: redis:7.4
    container_name: redis
    command: >
      redis-server
      --appendonly yes
      --protected-mode yes
      --aclfile /usr/local/etc/redis/users.acl
    volumes:
      - redis-data:/data
      - ./redis-users.acl:/usr/local/etc/redis/users.acl:ro
    restart: always

volumes:
  redis-data:
